pipeline {
    agent {
        docker {
            image 'python:2.7.18-slim'
        }
    }
    stages {
        stage('build') {
            steps {
                echo 'Build vote app'
                sh 'pip -i requirements.txt'
            }
        }
        stage('test') {
            steps{
                echo 'Testing vote app'
                sh 'nosetests -v'
            }
        }
    }
    post {
        always {
            echo 'Pipeline for vote app is completed...'
        }
    }
}
