version: "3.8"

volumes:
  db-data: 

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: koleesch/vote:master
    build: ./vote
    ports:
      - 5002:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:latest
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    image: koleesch/result:latest
    build: ./result
    ports:
      - 5003:4000
    networks:
      - instavote
    depends_on:
      - db

  worker:
    image: koleesch/worker:latest
    build: ./worker
    networks:
      - instavote
    depends_on:
      - redis
      - db
